### PR TITLE
Provide consuming movement methods so that NodeMut can act as a cursor.

### PR DESCRIPTION
**Pull request by adamreichold**
~~Still a draft because I added only the `into_next_sibling` method instead of handling all axes until we agreed that this is a helpful approach.~~ Added the missing methods after trying out a bit deduplication of internals.

### CODE REVIEW

**Comment by LoZack19** [comment]
This is perfect. As I said, `into_*` functions are very much needed in `NodeMut`, I like this approach

**Comment by cfvescovo** [comment]
This is an excellent approach! Huge thanks @adamreichold, your contributions are invaluable!

**Comment by LoZack19** [comment]
Excellent work! I appreciate the symmetry you've achieved. Additionally, I think the 'axisandinto_axis` functions enhance the code's readability.

**Review by LoZack19 — APPROVED** [review]
Excellent work! I appreciate the symmetry you've achieved. Additionally, I think the `axis` and `into_axis` functions enhance the code's readability.

**Comment by LoZack19** [comment]
Do you think that we could also take advantage of this to implement mutable and owned iterators for NodeMut?

**Comment by adamreichold** [comment]
> Do you think that we could also take advantage of this to implement mutable and owned iterators for NodeMut?

You mean something like

```rust
impl<'a, T: 'a> NodeMut<'a, T> {
  pub fn children(&self) -> ChildrenMut<'a, T>;
}
```

which yields distinct instances of `NodeMut<'a, T>` as items?

If so, then I don't think these methods help to implement this safely as while these methods can "advance" a `NodeMut` through the children of a given node, I cannot hand out that current `NodeMut` by returning it from `fn next(&mut self) -> Option<NodeMut<'a, T>>;` because I then have no basis to compute the next child node when `next` is called again.

This would only work with a lending iterator which yields a `&'b mut NodeMut<'a, T>` borrowing from `&'b self` which coincidentally is exactly the pattern that std's [`CursorMut::next`](https://doc.rust-lang.org/stable/std/collections/btree_map/struct.CursorMut.html#method.next) uses.

**Comment by adamreichold** [comment]
Realising how important it is to hold on to an existing mutable node reference, I added a second commit which extends the signature of these methods to

```rust
fn into_axis<F>(mut self, f: F) -> Result<Self, Self>;
```

return the current reference as `Err(self)` if navigation is not possible so that information is never lost if the calling code wants to recover from such a situation.

**Comment by adamreichold** [comment]
> It could still be useful, though, to have a mutable iterator which follows the [CursorMut::next](https://doc.rust-lang.org/stable/std/collections/btree_map/struct.CursorMut.html#method.next) pattern, as you suggested.

Note that this would not be an iterator though, i.e. not an implementation of the `Iterator` trait, because that trait cannot support lending (items can borrow from the container, but not from the iterator itself).

`NodeMut` basically is our equivalent to `CursorMut`, and our equivalent to `CursorMut::next` is

```rust
node = match node.into_next_sibling() {
  Ok(node) => node,
  Err(node) => node,
};
```

We could of course provide methods like

```rust
pub fn to_next_sibling(&mut self) -> Result<(), ()>;
```

which modify self in-place (or not if movement is not possible) instead of moving out of `self`. We could then implement the `into_*` methods on top of those.

Would you prefer that? If so, just the `to_*` variants or both `to_*` and `into_*`?

**Comment by cfvescovo** [comment]
> Realising how important it is to hold on to an existing mutable node reference, I added a second commit which extends the signature of these methods to
> 
> ```rust
> fn into_axis<F>(mut self, f: F) -> Result<Self, Self>;
> ```
> 
> return the current reference as `Err(self)` if navigation is not possible so that information is never lost if the calling code wants to recover from such a situation.

This is a good idea which would immensely benefit from better documentation

**Comment by cfvescovo** [comment]
> It could still be useful, though, to have a mutable iterator which follows the CursorMut::next pattern, as you suggested.

Agreed

**Comment by adamreichold** [comment]
> This is a good idea which would immensely benefit from better documentation

Will amend the documentation if we decide to stick to the `into_*` methods instead of switching over to `to_*`/in-place modification.

**Comment by LoZack19** [comment]
> Would you prefer that? If so, just the to_* variants or both to_* and into_*?

Personally I would love to have both implementations. I'm just a bit concerned about code duplication. I think that, to avoid overcomplicating the `NodeMut` API, it is convenient to abandon in-place modification through the `to_*` functions and stick to `into_*`

**Comment by LoZack19** [comment]
If you all agree, I approve to merge this PR into master

**Comment by adamreichold** [comment]
> When chosing, I prefer the alternative which hides the least state possible.

While trying, I also realized that the implement of `to_axis` is requires additional unsafe code to massage the lifetimes which another argument against it. So I guess we should indeed stick to the `into_*` methods and I will amend the doc comments w.r.t. the `Result<Self, Self>` pattern.

**Comment by adamreichold** [comment]
> If you all agree, I approve to merge this PR into master

I amended the docs as requests, so from my point of view, this is good to go.

**Comment by LoZack19** [comment]
Totally agree. Let's finish documenting this code and merge. I just want to point out that I have created a readme in which I try to summarize the design choises made in creating `ego-tree`, so possibly if there are choices to point out in this PR I would suggest doing so in the readme.md

**Comment by cfvescovo** [comment]
> Totally agree. Let's finish documenting this code and merge. I just want to point out that I have created a readme in which I try to summarize the design choises made in creating `ego-tree`, so possibly if there are choices to point out in this PR I would suggest doing so in the readme.md

@adamreichold rebase your branch on top of master

**Comment by cfvescovo** [comment]
Overall, I agree with you so, as soon as the docs situation is addressed, I will merge this

**Comment by cfvescovo** [comment]
I have rechecked, everything LGTM

**Comment by adamreichold** [comment]
Thanks. I would be glad if we could make a point release (for the `FusedIterator` impls) so that I could eventually recover the dependent `FusedIterator` impls in `scraper`.

**Comment by cfvescovo** [comment]
Releasing 0.80 ASAP

**Pull request merged**
